### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ceckles** [CodingGarden/next-travel-log#2]
pulled the repo, to verify, and I'm getting the same error as in the follow along project,
`ReferenceError: window is not defined
    at eval (webpack-internal:///(sc_client)/./node_modules/leaflet/dist/leaflet-src.js:229:19)
    at eval (webpack-internal:///(sc_client)/./node_modules/leaflet/dist/leaflet-src.js:7:11)
    at eval (webpack-internal:///(sc_client)/./node_modules/leaflet/dist/leaflet-src.js:9:3)
    at (sc_client)/./node_modules/leaflet/dist/leaflet-src.js (H:\next-travel-log-main\.next\server\app\page.js:494:1)
    at __webpack_require__ (H:\next-travel-log-main\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_client)/./node_modules/react-leaflet/lib/MapContainer.js:6:65)
    at (sc_client)/./node_modules/react-leaflet/lib/MapContainer.js (H:\next-travel-log-main\.next\server\app\page.js:2251:1)
    at __webpack_require__ (H:\next-travel-log-main\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_client)/./src/components/TravelLogMap.tsx:8:71)
    at (sc_client)/./src/components/TravelLogMap.tsx (H:\next-travel-log-main\.next\server\app\page.js:2086:1)
    at __webpack_require__ (H:\next-travel-log-main\.next\server\webpack-runtime.js:33:43)
    at requireModule (H:\next-travel-log-main\node_modules\next\dist\compiled\react-server-dom-webpack\client.js:142:32)
    at initializeModuleChunk (H:\next-travel-log-main\node_modules\next\dist\compiled\react-server-dom-webpack\client.js:427:19)
    at resolveModuleChunk (H:\next-travel-log-main\node_modules\next\dist\compiled\react-server-dom-webpack\client.js:385:5)
    at H:\next-travel-log-main\node_modules\next\dist\compiled\react-server-dom-webpack\client.js:668:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

also seems to be an issue with the map tile returns a couple dozen 404, and a cors error.
`Cross-Origin Read Blocking (CORB) blocked cross-origin response`
`3@2x:1          GET https://api.mapbox.com/styles/v1/codinggarden/cl84ukoao000p16o8u4zibr8d/tiles/256/3/1/3@2x?access_token=TOKEN 404 (Not Found)`

**Comment by w3cj** [comment]
Resolved today with: https://github.com/CodingGarden/next-travel-log/blob/main/src/app/page.tsx#L7
